preserve_hierarchy: true
export_languages: de

files:
  - source: /*.*
    ignore:
      - /*.csv
      - /*.xml
    translation: /translations/%two_letters_code%/%original_file_name%
    translation_replace:
      en.: 
      
  - source: /Multilingual_spreadsheet_sample.csv
    translation: /translations/%two_letters_code%/%original_file_name%
    first_line_contains_header: true
    scheme: identifier,context,source_phrase,es-ES,fr,de,it,max_length
    
  - source: /Sample.csv
    translation: /translations/%two_letters_code%/%original_file_name%
    first_line_contains_header: true
    scheme: identifier,context,source_phrase,translation
    
  - source: /Example._path_to_node.xml
    translation: /translations/%two_letters_code%/%original_file_name%
    translate_content: 0
    translate_attributes: 1
    content_segmentation: 0
    translatable_elements: 1
