preserve_hierarchy: true
export_languages: de

files:
  - source: /*.*
    ignore:
      - /*.csv
      - /*.xml
    translation: /translations/%two_letters_code%/%original_file_name%
    translation_replace:
      en.: 
  - source: /multicolumn.csv
    translation: /multicolumn.csv
    first_line_contains_header: true
    scheme: identifier,context,source_phrase,es_ES,fr,de,it,max.length
    
