preserve_hierarchy: true
export_languages: de

files:
  - source: /*.*
    ignore:
      - /*.csv
      - /*.xml
    translation: /translations/%two_letters_code%/%original_file_name%
    translation_replace:
      en.: 
      
  - source: /Multilingual_spreadsheet_sample.csv
    translation: /Multilingual_spreadsheet_sample.csv
    first_line_contains_header: true
    scheme: identifier,context,source_phrase,es-ES,fr,de,it,max_length
    
  - source: /Sample.csv
    translation: /Sample.csv
    first_line_contains_header: true
    scheme: identifier,context,source_phrase,translation
